'use strict';

const JOB_STATES = {
  QUEUED: 'QUEUED',
  STORY_VALIDATED: 'STORY_VALIDATED',
  VIDEO_CANDIDATE_REJECTED: 'VIDEO_CANDIDATE_REJECTED',
  STORY_UNDERSTOOD: 'STORY_UNDERSTOOD',
  EVIDENCE_PACKAGED: 'EVIDENCE_PACKAGED',
  SCRIPT_READY: 'SCRIPT_READY',
  VOICE_READY: 'VOICE_READY',
  MODULE_PLAN_READY: 'MODULE_PLAN_READY',
  SUBTITLES_READY: 'SUBTITLES_READY',
  READY_TO_REVIEW: 'READY_TO_REVIEW',
  RENDERING: 'RENDERING',
  RENDER_READY: 'RENDER_READY',
  READY_TO_PUBLISH: 'READY_TO_PUBLISH',
  PUBLISHED: 'PUBLISHED',
  FAILED: 'FAILED',
};

module.exports = { JOB_STATES };
