'use strict';

const JOB_STATES = {
  QUEUED: 'QUEUED',
  STORY_VALIDATED: 'STORY_VALIDATED',
  VIDEO_CANDIDATE_REJECTED: 'VIDEO_CANDIDATE_REJECTED',
  SCRIPT_GENERATING: 'SCRIPT_GENERATING',
  SCRIPT_READY: 'SCRIPT_READY',
  VOICE_GENERATING: 'VOICE_GENERATING',
  VOICE_READY: 'VOICE_READY',
  SCENE_PLAN_READY: 'SCENE_PLAN_READY',
  ASSETS_RESOLVING: 'ASSETS_RESOLVING',
  ASSETS_READY: 'ASSETS_READY',
  SUBTITLES_READY: 'SUBTITLES_READY',
  RENDERING: 'RENDERING',
  RENDER_READY: 'RENDER_READY',
  EXPORTING: 'EXPORTING',
  READY_TO_PUBLISH: 'READY_TO_PUBLISH',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  PUBLISHING: 'PUBLISHING',
  PUBLISHED: 'PUBLISHED',
  FAILED: 'FAILED',
};

module.exports = {
  JOB_STATES,
};
